query common_product($id: ID!){
  common_product(id: $id) {
    id
    name
    cover
    desc
    images
    processing_company {
      id
      name
      remark
      created_at
      updated_at
    }
    status
    remark
    content
    sort
    created_at
    updated_at
  }
}
