query expert_system_staffs{
  expert_system_staffs {
    id
    expert_system_staff_category {
      id
      name
      expert_system_staff_number
      created_at
      updated_at
    }
    avatar
    name
    job_title
    work_unit
    expertise
    article_number
    question_number
    created_at
    updated_at
  }
}