query traceability_material_output_list($input: TraceabilityMaterialOutputListInput!){
  traceability_material_output_list(input: $input) {
    current_page
    last_page
    total
    limit
    items {
      id
      material_input {
        id
        category{
          name
          unit
          id
        }
        batch
        cover
        number
        residual
      }
      cover
      number
      receiver
      manager
      created_at
      updated_at
    }
  }
}
