query traceability_material_list($input: TraceabilityMaterialListInput!){
  traceability_material_list(input: $input) {
    current_page
    last_page
    total
    limit
    items {
      id
      name
      category
      created_at
      updated_at
    }
  }
}
