query traceability_plot_land_list($input: TraceabilityPlotLandListInput!){
  traceability_plot_land_list(input: $input) {
    current_page
    last_page
    total
    limit
    items {
      id
      title
      code
      farmer{
        name
      }
      created_at
      updated_at
    }
  }
}
