query traceability_material_input($id: ID!){
  traceability_material_input(id: $id) {
    id
    category{
      id
      name
    }
    batch
    cover
    number
    remark
    residual
    created_at
    updated_at
  }
}
