query traceability_product_input_list($input: TraceabilityProductInputListInput!){
  traceability_product_input_list(input: $input) {
    current_page
    last_page
    total
    limit
    items {
      id
      product {
        id
        name
      }
      plot_land {
        id
        title
        code
      }
      batch
      unit
      number
      status
      created_at
      updated_at
    }
  }
}
