query common_shop_product_list($input: CommonShopProductListInput!){
  common_shop_product_list(input: $input) {
    current_page
    last_page
    total
    limit
    items {
      id
      name
      price
      company
      status
      sort
      created_at
      updated_at
    }
  }
}
